// <auto-generated>
// Generated from events/catalog.yaml — do not edit by hand.
// Regenerate: go run ./cmd/analytics-server gen-events
// </auto-generated>

using System.Collections.Generic;

namespace Mortris.Events
{
    public static class MortrisEvents
    {
        public static class Names
        {
            public const string SysSessionStart = "sys_session_start";
            public const string SysAppBackground = "sys_app_background";
            public const string SysSdkHealth = "sys_sdk_health";
        }

        // Emitted at most once per session. Bounded counters only — must never contain exception text, URLs, or event properties from Track calls.
        public static Dictionary<string, object> BuildSysSdkHealth(double handoffDrops, double queueEvictions, double permanentRejections, double corruptionResets, double retryCount, string lastUploadCategory)
        {
            var properties = new Dictionary<string, object>();
            properties["handoff_drops"] = handoffDrops;
            properties["queue_evictions"] = queueEvictions;
            properties["permanent_rejections"] = permanentRejections;
            properties["corruption_resets"] = corruptionResets;
            properties["retry_count"] = retryCount;
            properties["last_upload_category"] = lastUploadCategory;
            return properties;
        }
    }
}
