package codegen

import (
	"fmt"
	"strings"
	"unicode"
)

// GenerateCSharp renders catalog as a MortrisEvents static class: a
// Names constant per event (compile-time-safe event names) plus, for
// events with declared properties, a typed builder method returning the
// property bag the SDK's Track() call expects.
func GenerateCSharp(catalog *Catalog) string {
	var b strings.Builder
	b.WriteString("// <auto-generated>\n")
	b.WriteString("// Generated from events/catalog.yaml — do not edit by hand.\n")
	b.WriteString("// Regenerate: go run ./cmd/analytics-server gen-events\n")
	b.WriteString("// </auto-generated>\n\n")
	b.WriteString("using System.Collections.Generic;\n\n")
	b.WriteString("namespace Mortris.Events\n{\n")
	b.WriteString("    public static class MortrisEvents\n    {\n")

	b.WriteString("        public static class Names\n        {\n")
	for _, e := range catalog.Events {
		fmt.Fprintf(&b, "            public const string %s = \"%s\";\n", pascalCase(e.Name), e.Name)
	}
	b.WriteString("        }\n")

	for _, e := range catalog.Events {
		if len(e.Properties) == 0 {
			continue
		}
		b.WriteString("\n")
		writeBuilder(&b, e)
	}

	b.WriteString("    }\n}\n")
	return b.String()
}

func writeBuilder(b *strings.Builder, e EventDef) {
	required, optional := splitProperties(e.Properties)
	params := make([]string, 0, len(e.Properties))
	for _, p := range required {
		params = append(params, fmt.Sprintf("%s %s", csharpType(p.Type, false), camelCase(p.Name)))
	}
	for _, p := range optional {
		params = append(params, fmt.Sprintf("%s %s = null", csharpType(p.Type, true), camelCase(p.Name)))
	}

	if e.Description != "" {
		fmt.Fprintf(b, "        // %s\n", strings.ReplaceAll(strings.TrimSpace(e.Description), "\n", " "))
	}
	fmt.Fprintf(b, "        public static Dictionary<string, object> Build%s(%s)\n", pascalCase(e.Name), strings.Join(params, ", "))
	b.WriteString("        {\n")
	b.WriteString("            var properties = new Dictionary<string, object>();\n")
	for _, p := range required {
		fmt.Fprintf(b, "            properties[\"%s\"] = %s;\n", p.Name, camelCase(p.Name))
	}
	for _, p := range optional {
		name := camelCase(p.Name)
		fmt.Fprintf(b, "            if (%s != null) properties[\"%s\"] = %s;\n", name, p.Name, name)
	}
	b.WriteString("            return properties;\n")
	b.WriteString("        }\n")
}

func splitProperties(properties []PropertyDef) (required, optional []PropertyDef) {
	for _, p := range properties {
		if p.Required {
			required = append(required, p)
		} else {
			optional = append(optional, p)
		}
	}
	return required, optional
}

// csharpType maps the catalog's three property types (events/catalog.yaml
// header: string | number | boolean) to C#. nullable wraps value types in
// "?" so an unset optional property has a real absent state, not a
// type-specific sentinel.
func csharpType(kind string, nullable bool) string {
	base := "object"
	switch kind {
	case "string":
		base = "string"
	case "number":
		base = "double"
	case "boolean":
		base = "bool"
	}
	if nullable && base != "string" && base != "object" {
		return base + "?"
	}
	if nullable {
		return base
	}
	return base
}

// pascalCase turns a snake_case catalog name into a C# identifier:
// sys_session_start -> SysSessionStart.
func pascalCase(s string) string {
	return identifier(s, true)
}

// camelCase turns a catalog property name into a C# parameter name:
// handoff_drops -> handoffDrops. Property names may already contain mixed
// case (events/catalog.yaml allows ^[a-zA-Z0-9_]{1,64}$), so only
// underscore-separated segments are re-cased.
func camelCase(s string) string {
	return identifier(s, false)
}

func identifier(s string, pascal bool) string {
	segments := strings.FieldsFunc(s, func(r rune) bool { return r == '_' })
	var b strings.Builder
	for i, seg := range segments {
		if seg == "" {
			continue
		}
		if i == 0 && !pascal {
			b.WriteString(strings.ToLower(seg[:1]) + seg[1:])
			continue
		}
		r := []rune(seg)
		b.WriteRune(unicode.ToUpper(r[0]))
		b.WriteString(string(r[1:]))
	}
	out := b.String()
	if out == "" {
		return "_"
	}
	if unicode.IsDigit(rune(out[0])) {
		out = "_" + out
	}
	return out
}
